// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protos.proto

//go:build protoopaque

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthAction int32

const (
	AuthAction_A_NONE  AuthAction = 0
	AuthAction_A_READ  AuthAction = 1
	AuthAction_A_WRITE AuthAction = 2
)

// Enum value maps for AuthAction.
var (
	AuthAction_name = map[int32]string{
		0: "A_NONE",
		1: "A_READ",
		2: "A_WRITE",
	}
	AuthAction_value = map[string]int32{
		"A_NONE":  0,
		"A_READ":  1,
		"A_WRITE": 2,
	}
)

func (x AuthAction) Enum() *AuthAction {
	p := new(AuthAction)
	*p = x
	return p
}

func (x AuthAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthAction) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_proto_enumTypes[0].Descriptor()
}

func (AuthAction) Type() protoreflect.EnumType {
	return &file_protos_proto_enumTypes[0]
}

func (x AuthAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Digests struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sha1        []byte                 `protobuf:"bytes,1,opt,name=sha1"`
	xxx_hidden_Md5         []byte                 `protobuf:"bytes,2,opt,name=md5"`
	xxx_hidden_Sha256      []byte                 `protobuf:"bytes,3,opt,name=sha256"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Digests) Reset() {
	*x = Digests{}
	mi := &file_protos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digests) ProtoMessage() {}

func (x *Digests) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Digests) GetSha1() []byte {
	if x != nil {
		return x.xxx_hidden_Sha1
	}
	return nil
}

func (x *Digests) GetMd5() []byte {
	if x != nil {
		return x.xxx_hidden_Md5
	}
	return nil
}

func (x *Digests) GetSha256() []byte {
	if x != nil {
		return x.xxx_hidden_Sha256
	}
	return nil
}

func (x *Digests) SetSha1(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sha1 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Digests) SetMd5(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Md5 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Digests) SetSha256(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sha256 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Digests) HasSha1() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Digests) HasMd5() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Digests) HasSha256() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Digests) ClearSha1() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Sha1 = nil
}

func (x *Digests) ClearMd5() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Md5 = nil
}

func (x *Digests) ClearSha256() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Sha256 = nil
}

type Digests_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sha1   []byte
	Md5    []byte
	Sha256 []byte
}

func (b0 Digests_builder) Build() *Digests {
	m0 := &Digests{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Sha1 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Sha1 = b.Sha1
	}
	if b.Md5 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Md5 = b.Md5
	}
	if b.Sha256 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Sha256 = b.Sha256
	}
	return m0
}

type DirectoryEntry struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Blake3Hash            []byte                 `protobuf:"bytes,1,opt,name=blake3_hash,json=blake3Hash"`
	xxx_hidden_ModuleType            *string                `protobuf:"bytes,2,opt,name=module_type,json=moduleType"`
	xxx_hidden_LastModifiedTimestamp int64                  `protobuf:"varint,3,opt,name=last_modified_timestamp,json=lastModifiedTimestamp"`
	xxx_hidden_Digests               *Digests               `protobuf:"bytes,4,opt,name=digests"`
	xxx_hidden_DataSize              int64                  `protobuf:"varint,5,opt,name=data_size,json=dataSize"`
	xxx_hidden_External              bool                   `protobuf:"varint,6,opt,name=external"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DirectoryEntry) Reset() {
	*x = DirectoryEntry{}
	mi := &file_protos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryEntry) ProtoMessage() {}

func (x *DirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DirectoryEntry) GetBlake3Hash() []byte {
	if x != nil {
		return x.xxx_hidden_Blake3Hash
	}
	return nil
}

func (x *DirectoryEntry) GetModuleType() string {
	if x != nil {
		if x.xxx_hidden_ModuleType != nil {
			return *x.xxx_hidden_ModuleType
		}
		return ""
	}
	return ""
}

func (x *DirectoryEntry) GetLastModifiedTimestamp() int64 {
	if x != nil {
		return x.xxx_hidden_LastModifiedTimestamp
	}
	return 0
}

func (x *DirectoryEntry) GetDigests() *Digests {
	if x != nil {
		return x.xxx_hidden_Digests
	}
	return nil
}

func (x *DirectoryEntry) GetDataSize() int64 {
	if x != nil {
		return x.xxx_hidden_DataSize
	}
	return 0
}

func (x *DirectoryEntry) GetExternal() bool {
	if x != nil {
		return x.xxx_hidden_External
	}
	return false
}

func (x *DirectoryEntry) SetBlake3Hash(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Blake3Hash = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *DirectoryEntry) SetModuleType(v string) {
	x.xxx_hidden_ModuleType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *DirectoryEntry) SetLastModifiedTimestamp(v int64) {
	x.xxx_hidden_LastModifiedTimestamp = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *DirectoryEntry) SetDigests(v *Digests) {
	x.xxx_hidden_Digests = v
}

func (x *DirectoryEntry) SetDataSize(v int64) {
	x.xxx_hidden_DataSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *DirectoryEntry) SetExternal(v bool) {
	x.xxx_hidden_External = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *DirectoryEntry) HasBlake3Hash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DirectoryEntry) HasModuleType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DirectoryEntry) HasLastModifiedTimestamp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DirectoryEntry) HasDigests() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Digests != nil
}

func (x *DirectoryEntry) HasDataSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *DirectoryEntry) HasExternal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DirectoryEntry) ClearBlake3Hash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Blake3Hash = nil
}

func (x *DirectoryEntry) ClearModuleType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ModuleType = nil
}

func (x *DirectoryEntry) ClearLastModifiedTimestamp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_LastModifiedTimestamp = 0
}

func (x *DirectoryEntry) ClearDigests() {
	x.xxx_hidden_Digests = nil
}

func (x *DirectoryEntry) ClearDataSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_DataSize = 0
}

func (x *DirectoryEntry) ClearExternal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_External = false
}

type DirectoryEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Blake3Hash            []byte
	ModuleType            *string
	LastModifiedTimestamp *int64
	Digests               *Digests
	DataSize              *int64
	External              *bool
}

func (b0 DirectoryEntry_builder) Build() *DirectoryEntry {
	m0 := &DirectoryEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Blake3Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Blake3Hash = b.Blake3Hash
	}
	if b.ModuleType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_ModuleType = b.ModuleType
	}
	if b.LastModifiedTimestamp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_LastModifiedTimestamp = *b.LastModifiedTimestamp
	}
	x.xxx_hidden_Digests = b.Digests
	if b.DataSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_DataSize = *b.DataSize
	}
	if b.External != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_External = *b.External
	}
	return m0
}

type PathList struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Paths []string               `protobuf:"bytes,1,rep,name=paths"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PathList) Reset() {
	*x = PathList{}
	mi := &file_protos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathList) ProtoMessage() {}

func (x *PathList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PathList) GetPaths() []string {
	if x != nil {
		return x.xxx_hidden_Paths
	}
	return nil
}

func (x *PathList) SetPaths(v []string) {
	x.xxx_hidden_Paths = v
}

type PathList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Paths []string
}

func (b0 PathList_builder) Build() *PathList {
	m0 := &PathList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Paths = b.Paths
	return m0
}

type HashEntry struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State isHashEntry_State      `protobuf_oneof:"state"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HashEntry) Reset() {
	*x = HashEntry{}
	mi := &file_protos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashEntry) ProtoMessage() {}

func (x *HashEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HashEntry) GetInlinePaths() *PathList {
	if x != nil {
		if x, ok := x.xxx_hidden_State.(*hashEntry_InlinePaths); ok {
			return x.InlinePaths
		}
	}
	return nil
}

func (x *HashEntry) GetRefcount() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_State.(*hashEntry_Refcount); ok {
			return x.Refcount
		}
	}
	return 0
}

func (x *HashEntry) SetInlinePaths(v *PathList) {
	if v == nil {
		x.xxx_hidden_State = nil
		return
	}
	x.xxx_hidden_State = &hashEntry_InlinePaths{v}
}

func (x *HashEntry) SetRefcount(v int64) {
	x.xxx_hidden_State = &hashEntry_Refcount{v}
}

func (x *HashEntry) HasState() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_State != nil
}

func (x *HashEntry) HasInlinePaths() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_State.(*hashEntry_InlinePaths)
	return ok
}

func (x *HashEntry) HasRefcount() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_State.(*hashEntry_Refcount)
	return ok
}

func (x *HashEntry) ClearState() {
	x.xxx_hidden_State = nil
}

func (x *HashEntry) ClearInlinePaths() {
	if _, ok := x.xxx_hidden_State.(*hashEntry_InlinePaths); ok {
		x.xxx_hidden_State = nil
	}
}

func (x *HashEntry) ClearRefcount() {
	if _, ok := x.xxx_hidden_State.(*hashEntry_Refcount); ok {
		x.xxx_hidden_State = nil
	}
}

const HashEntry_State_not_set_case case_HashEntry_State = 0
const HashEntry_InlinePaths_case case_HashEntry_State = 1
const HashEntry_Refcount_case case_HashEntry_State = 2

func (x *HashEntry) WhichState() case_HashEntry_State {
	if x == nil {
		return HashEntry_State_not_set_case
	}
	switch x.xxx_hidden_State.(type) {
	case *hashEntry_InlinePaths:
		return HashEntry_InlinePaths_case
	case *hashEntry_Refcount:
		return HashEntry_Refcount_case
	default:
		return HashEntry_State_not_set_case
	}
}

type HashEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_State:
	InlinePaths *PathList
	Refcount    *int64
	// -- end of xxx_hidden_State
}

func (b0 HashEntry_builder) Build() *HashEntry {
	m0 := &HashEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InlinePaths != nil {
		x.xxx_hidden_State = &hashEntry_InlinePaths{b.InlinePaths}
	}
	if b.Refcount != nil {
		x.xxx_hidden_State = &hashEntry_Refcount{*b.Refcount}
	}
	return m0
}

type case_HashEntry_State protoreflect.FieldNumber

func (x case_HashEntry_State) String() string {
	md := file_protos_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isHashEntry_State interface {
	isHashEntry_State()
}

type hashEntry_InlinePaths struct {
	InlinePaths *PathList `protobuf:"bytes,1,opt,name=inline_paths,json=inlinePaths,oneof"`
}

type hashEntry_Refcount struct {
	Refcount int64 `protobuf:"varint,2,opt,name=refcount,oneof"`
}

func (*hashEntry_InlinePaths) isHashEntry_State() {}

func (*hashEntry_Refcount) isHashEntry_State() {}

type Asset struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Truncated    bool                   `protobuf:"varint,2,opt,name=truncated"`
	xxx_hidden_Data         []byte                 `protobuf:"bytes,3,opt,name=data"`
	xxx_hidden_OriginalSize int64                  `protobuf:"varint,4,opt,name=original_size,json=originalSize"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_protos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Asset) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Asset) GetTruncated() bool {
	if x != nil {
		return x.xxx_hidden_Truncated
	}
	return false
}

func (x *Asset) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Asset) GetOriginalSize() int64 {
	if x != nil {
		return x.xxx_hidden_OriginalSize
	}
	return 0
}

func (x *Asset) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Asset) SetTruncated(v bool) {
	x.xxx_hidden_Truncated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Asset) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Asset) SetOriginalSize(v int64) {
	x.xxx_hidden_OriginalSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Asset) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Asset) HasTruncated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Asset) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Asset) HasOriginalSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Asset) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Asset) ClearTruncated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Truncated = false
}

func (x *Asset) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Data = nil
}

func (x *Asset) ClearOriginalSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OriginalSize = 0
}

type Asset_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         *string
	Truncated    *bool
	Data         []byte
	OriginalSize *int64
}

func (b0 Asset_builder) Build() *Asset {
	m0 := &Asset{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Truncated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Truncated = *b.Truncated
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Data = b.Data
	}
	if b.OriginalSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_OriginalSize = *b.OriginalSize
	}
	return m0
}

type TestRecord struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TestId       int64                  `protobuf:"varint,1,opt,name=test_id,json=testId"`
	xxx_hidden_Input        *Asset                 `protobuf:"bytes,2,opt,name=input"`
	xxx_hidden_Output       *Asset                 `protobuf:"bytes,3,opt,name=output"`
	xxx_hidden_Answer       *Asset                 `protobuf:"bytes,4,opt,name=answer"`
	xxx_hidden_TesterOutput *Asset                 `protobuf:"bytes,5,opt,name=tester_output,json=testerOutput"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TestRecord) Reset() {
	*x = TestRecord{}
	mi := &file_protos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRecord) ProtoMessage() {}

func (x *TestRecord) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TestRecord) GetTestId() int64 {
	if x != nil {
		return x.xxx_hidden_TestId
	}
	return 0
}

func (x *TestRecord) GetInput() *Asset {
	if x != nil {
		return x.xxx_hidden_Input
	}
	return nil
}

func (x *TestRecord) GetOutput() *Asset {
	if x != nil {
		return x.xxx_hidden_Output
	}
	return nil
}

func (x *TestRecord) GetAnswer() *Asset {
	if x != nil {
		return x.xxx_hidden_Answer
	}
	return nil
}

func (x *TestRecord) GetTesterOutput() *Asset {
	if x != nil {
		return x.xxx_hidden_TesterOutput
	}
	return nil
}

func (x *TestRecord) SetTestId(v int64) {
	x.xxx_hidden_TestId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *TestRecord) SetInput(v *Asset) {
	x.xxx_hidden_Input = v
}

func (x *TestRecord) SetOutput(v *Asset) {
	x.xxx_hidden_Output = v
}

func (x *TestRecord) SetAnswer(v *Asset) {
	x.xxx_hidden_Answer = v
}

func (x *TestRecord) SetTesterOutput(v *Asset) {
	x.xxx_hidden_TesterOutput = v
}

func (x *TestRecord) HasTestId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TestRecord) HasInput() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Input != nil
}

func (x *TestRecord) HasOutput() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Output != nil
}

func (x *TestRecord) HasAnswer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Answer != nil
}

func (x *TestRecord) HasTesterOutput() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TesterOutput != nil
}

func (x *TestRecord) ClearTestId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TestId = 0
}

func (x *TestRecord) ClearInput() {
	x.xxx_hidden_Input = nil
}

func (x *TestRecord) ClearOutput() {
	x.xxx_hidden_Output = nil
}

func (x *TestRecord) ClearAnswer() {
	x.xxx_hidden_Answer = nil
}

func (x *TestRecord) ClearTesterOutput() {
	x.xxx_hidden_TesterOutput = nil
}

type TestRecord_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TestId       *int64
	Input        *Asset
	Output       *Asset
	Answer       *Asset
	TesterOutput *Asset
}

func (b0 TestRecord_builder) Build() *TestRecord {
	m0 := &TestRecord{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TestId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_TestId = *b.TestId
	}
	x.xxx_hidden_Input = b.Input
	x.xxx_hidden_Output = b.Output
	x.xxx_hidden_Answer = b.Answer
	x.xxx_hidden_TesterOutput = b.TesterOutput
	return m0
}

type TestingRecord struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Solution *Asset                 `protobuf:"bytes,1,opt,name=solution"`
	xxx_hidden_Test     *[]*TestRecord         `protobuf:"bytes,2,rep,name=test"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TestingRecord) Reset() {
	*x = TestingRecord{}
	mi := &file_protos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingRecord) ProtoMessage() {}

func (x *TestingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_protos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TestingRecord) GetSolution() *Asset {
	if x != nil {
		return x.xxx_hidden_Solution
	}
	return nil
}

func (x *TestingRecord) GetTest() []*TestRecord {
	if x != nil {
		if x.xxx_hidden_Test != nil {
			return *x.xxx_hidden_Test
		}
	}
	return nil
}

func (x *TestingRecord) SetSolution(v *Asset) {
	x.xxx_hidden_Solution = v
}

func (x *TestingRecord) SetTest(v []*TestRecord) {
	x.xxx_hidden_Test = &v
}

func (x *TestingRecord) HasSolution() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Solution != nil
}

func (x *TestingRecord) ClearSolution() {
	x.xxx_hidden_Solution = nil
}

type TestingRecord_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Solution *Asset
	Test     []*TestRecord
}

func (b0 TestingRecord_builder) Build() *TestingRecord {
	m0 := &TestingRecord{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Solution = b.Solution
	x.xxx_hidden_Test = &b.Test
	return m0
}

var File_protos_proto protoreflect.FileDescriptor

const file_protos_proto_rawDesc = "" +
	"\n" +
	"\fprotos.proto\x12\x06protos\x1a!google/protobuf/go_features.proto\"G\n" +
	"\aDigests\x12\x12\n" +
	"\x04sha1\x18\x01 \x01(\fR\x04sha1\x12\x10\n" +
	"\x03md5\x18\x02 \x01(\fR\x03md5\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\"\xee\x01\n" +
	"\x0eDirectoryEntry\x12\x1f\n" +
	"\vblake3_hash\x18\x01 \x01(\fR\n" +
	"blake3Hash\x12\x1f\n" +
	"\vmodule_type\x18\x02 \x01(\tR\n" +
	"moduleType\x126\n" +
	"\x17last_modified_timestamp\x18\x03 \x01(\x03R\x15lastModifiedTimestamp\x12)\n" +
	"\adigests\x18\x04 \x01(\v2\x0f.protos.DigestsR\adigests\x12\x1b\n" +
	"\tdata_size\x18\x05 \x01(\x03R\bdataSize\x12\x1a\n" +
	"\bexternal\x18\x06 \x01(\bR\bexternal\" \n" +
	"\bPathList\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"i\n" +
	"\tHashEntry\x125\n" +
	"\finline_paths\x18\x01 \x01(\v2\x10.protos.PathListH\x00R\vinlinePaths\x12\x1c\n" +
	"\brefcount\x18\x02 \x01(\x03H\x00R\brefcountB\a\n" +
	"\x05state\"r\n" +
	"\x05Asset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12#\n" +
	"\roriginal_size\x18\x04 \x01(\x03R\foriginalSize\"\xcc\x01\n" +
	"\n" +
	"TestRecord\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\x03R\x06testId\x12#\n" +
	"\x05input\x18\x02 \x01(\v2\r.protos.AssetR\x05input\x12%\n" +
	"\x06output\x18\x03 \x01(\v2\r.protos.AssetR\x06output\x12%\n" +
	"\x06answer\x18\x04 \x01(\v2\r.protos.AssetR\x06answer\x122\n" +
	"\rtester_output\x18\x05 \x01(\v2\r.protos.AssetR\ftesterOutput\"b\n" +
	"\rTestingRecord\x12)\n" +
	"\bsolution\x18\x01 \x01(\v2\r.protos.AssetR\bsolution\x12&\n" +
	"\x04test\x18\x02 \x03(\v2\x12.protos.TestRecordR\x04test*1\n" +
	"\n" +
	"AuthAction\x12\n" +
	"\n" +
	"\x06A_NONE\x10\x00\x12\n" +
	"\n" +
	"\x06A_READ\x10\x01\x12\v\n" +
	"\aA_WRITE\x10\x02B0Z$github.com/contester/advfiler/protos\x92\x03\a\xd2>\x02\x10\x02 \x03b\beditionsp\xe9\a"

var file_protos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_proto_goTypes = []any{
	(AuthAction)(0),        // 0: protos.AuthAction
	(*Digests)(nil),        // 1: protos.Digests
	(*DirectoryEntry)(nil), // 2: protos.DirectoryEntry
	(*PathList)(nil),       // 3: protos.PathList
	(*HashEntry)(nil),      // 4: protos.HashEntry
	(*Asset)(nil),          // 5: protos.Asset
	(*TestRecord)(nil),     // 6: protos.TestRecord
	(*TestingRecord)(nil),  // 7: protos.TestingRecord
}
var file_protos_proto_depIdxs = []int32{
	1, // 0: protos.DirectoryEntry.digests:type_name -> protos.Digests
	3, // 1: protos.HashEntry.inline_paths:type_name -> protos.PathList
	5, // 2: protos.TestRecord.input:type_name -> protos.Asset
	5, // 3: protos.TestRecord.output:type_name -> protos.Asset
	5, // 4: protos.TestRecord.answer:type_name -> protos.Asset
	5, // 5: protos.TestRecord.tester_output:type_name -> protos.Asset
	5, // 6: protos.TestingRecord.solution:type_name -> protos.Asset
	6, // 7: protos.TestingRecord.test:type_name -> protos.TestRecord
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_protos_proto_init() }
func file_protos_proto_init() {
	if File_protos_proto != nil {
		return
	}
	file_protos_proto_msgTypes[3].OneofWrappers = []any{
		(*hashEntry_InlinePaths)(nil),
		(*hashEntry_Refcount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_proto_rawDesc), len(file_protos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_proto_goTypes,
		DependencyIndexes: file_protos_proto_depIdxs,
		EnumInfos:         file_protos_proto_enumTypes,
		MessageInfos:      file_protos_proto_msgTypes,
	}.Build()
	File_protos_proto = out.File
	file_protos_proto_goTypes = nil
	file_protos_proto_depIdxs = nil
}
